# Form implementation generated from reading ui file 'addconfig.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addconfig(object):
    def setupUi(self, addconfig):
        addconfig.setObjectName("addconfig")
        addconfig.resize(340, 82)
        self.verticalLayout = QtWidgets.QVBoxLayout(addconfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cfgname_label = QtWidgets.QLabel(addconfig)
        self.cfgname_label.setObjectName("cfgname_label")
        self.horizontalLayout.addWidget(self.cfgname_label)
        self.name_lineedit = QtWidgets.QLineEdit(addconfig)
        self.name_lineedit.setObjectName("name_lineedit")
        self.horizontalLayout.addWidget(self.name_lineedit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(addconfig)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(addconfig)
        self.buttonBox.accepted.connect(addconfig.accept) # type: ignore
        self.buttonBox.rejected.connect(addconfig.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addconfig)

    def retranslateUi(self, addconfig):
        _translate = QtCore.QCoreApplication.translate
        addconfig.setWindowTitle(_translate("addconfig", "Dialog"))
        self.cfgname_label.setText(_translate("addconfig", "Configuration name:"))
